apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: s3read-write-test-secret
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: mcscloud/spark-py:webinar_spark_k8s
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/custom_jobs/s3read_write.py
  sparkVersion: "3.0.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.1
    serviceAccount: spark
    env:
    - name: "S3_PATH"
      value: "s3a://s3-demo/evo_train_new.csv"
    - name: "S3_WRITE_PATH"
      value: "s3a://s3-demo/write/evo_train_csv/"
    envFrom:
    - secretRef:
        name: s3-secret
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.1
    env:
    - name: "S3_PATH"
      value: "s3a://s3-demo/evo_train_new.csv"
    - name: "S3_WRITE_PATH"
      value: "s3a://s3-demo/write/evo_train_csv/"
    envFrom:
    - secretRef:
        name: s3-secret