apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: s3read-test-one
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: mcscloud/spark-py:webinar_spark_k8s
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/custom_jobs/s3read.py
  sparkVersion: "3.0.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.1
    serviceAccount: spark
    #Don`t do this in production. Save creds in Secret
    env:
    - name: S3_ACCESS_KEY
      value: "PLACE_ACCESS_KEY_HERE"
    - name: "S3_SECRET_KEY"
      value: "PLACE_SECRET_KEY_HERE"
    - name: "S3_PATH"
      value: "s3a://s3-demo/evo_train_new.csv"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.1
    #Don`t do this in production. Save creds in Secret
    env:
    - name: "S3_ACCESS_KEY"
      value: "PLACE_ACCESS_KEY_HERE"
    - name: "S3_SECRET_KEY"
      value: "PLACE_SECRET_KEY_HERE"
    - name: "S3_PATH"
      value: "s3a://s3-demo/evo_train_new.csv"
